version: '2.1'

services:

  mediaserver:
    image: nginx:1.15-alpine
    environment:
      NGINX_CONF: |-
        server {
          listen 80;

          access_log /var/log/nginx/access.log main;

          location /static/files {
            sendfile on;
            tcp_nopush on;
            gzip on;
            gzip_types text/plain application/x-javascript text/css;
            expires 30d;
            alias /var/local/meetings/instance/files;
          }
        }
    depends_on:
      - app
    volumes:
      - app-files:/var/local/meetings/instance/files/:ro
    command: /bin/sh -c 'echo "$$NGINX_CONF" > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'

  app:
    image: eaudeweb/mrt:2.9.4
    env_file:
      - docker/app.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./settings.py:/var/local/meetings/instance/settings.py:ro
      - app-files:/var/local/meetings/instance/files

  async:
    image: eaudeweb/mrt:2.9.4
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./settings.py:/var/local/meetings/instance/settings.py:ro
      - app-files:/var/local/meetings/instance/files
    command: ["rq", "workers", "printouts"]

  redis:
    image: redis:3.2.11-alpine
    healthcheck:
      test: "redis-cli -h 127.0.0.1 ping"
      interval: 30s
      timeout: 30s
      retries: 3

  db:
    image: postgres:10-alpine
    env_file:
      - docker/db.env
    volumes:
      - app-data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  app-files:
    driver: local
  app-data:
    driver: local
