mrt:
  image: eaudeweb/mrt
  ports:
  - "80:5000"
  links:
  - postgres:postgres
  - redis:redis
  volumes:
  - mrt-files-logos:/var/local/meetings/instance/files/logos
  - mrt-files-printouts:/var/local/meetings/instance/files/printouts
  - /etc/localtime:/etc/localtime:ro
  - ./settings.py:/var/local/meetings/instance/settings.py:ro

async:
  image: eaudeweb/mrt
  links:
  - redis:redis
  - postgres:postgres
  volumes:
  - /var/local/meetings/.skip-db-init
  - mrt-files-logos:/var/local/meetings/instance/files/logos
  - mrt-files-printouts:/var/local/meetings/instance/files/printouts
  - /etc/localtime:/etc/localtime:ro
  - ./settings.py:/var/local/meetings/instance/settings.py:ro
  command: ["rq", "workers", "printouts"]

redis:
  image: redis

postgres:
  image: eeacms/postgres:9.5s
  environment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_DBNAME=meetings
  - POSTGRES_DBUSER=edw
  - POSTGRES_DBPASS=edw
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - mrt-postgres-data:/var/lib/postgresql/data
