version: '2.1'

services:

  mediaserver:
    container_name: mrt.nginx
    restart: unless-stopped
    environment:
     - LOGSPOUT=ignore

  app:
    container_name: mrt.app
    restart: unless-stopped
    environment:
     - FLASK_MIGRATE=no
     - FLASK_CREATE_SUPERUSER=no
     - UWSGI_PORT=5000
     - DOMAIN_NAME=https://meetings.cms.int
    healthcheck:
      test: "curl -f --max-time 1 http://localhost:$$UWSGI_PORT/healthcheck || exit 1"
      interval: 10s
      timeout: 2s
      retries: 3

  async:
    container_name: mrt.rq
    restart: unless-stopped
    environment:
     - DOMAIN_NAME=http://app:5000

  redis:
    container_name: mrt.redis
    restart: unless-stopped

  db:
    container_name: mrt.db
    restart: unless-stopped

  log:
    image: gliderlabs/logspout:v3.2.5
    container_name: mrt.logs
    restart: unless-stopped
    environment:
     - SYSLOG_HOSTNAME=${HOSTNAME}_{{ index .Container.Config.Labels "com.docker.compose.project"}}
     - LOGSPOUT=ignore
    env_file:
      - docker/log.env
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    command: 'syslog://$${HOST}:$${PORT}?filter.name=$${FILTER}'
