version: '2'

services:

  mrt:
    image: eaudeweb/mrt:latest
    container_name: mrt.app
    ports:
    - "5000:5000"
    links:
    - postgres:postgres
    - redis:redis
    volumes:
    - ./settings.py:/var/local/meetings/instance/settings.py:ro
    - mrt-files:/var/local/meetings/instance/files

  async:
    image: eaudeweb/mrt:latest
    container_name: mrt.rq
    links:
    - redis:redis
    - postgres:postgres
    volumes:
    - /var/local/meetings/.skip-db-init
    - ./settings.py:/var/local/meetings/instance/settings.py:ro
    - mrt-files:/var/local/meetings/instance/files/
    command: ["rq", "workers", "printouts"]

  redis:
    image: redis:3.2.10-alpine
    container_name: mrt.redis

  postgres:
    image: eeacms/postgres:9.6-3.0
    container_name: mrt.db
    env_file:
    - docker/postgres.env
    volumes:
    - mrt-data:/var/lib/postgresql/data

  logspout:
    image: gliderlabs/logspout:v3.2.2
    container_name: mrt.logs
    command: 'syslog://$${HOST}:$${PORT}?filter.name=mrt.*'
    env_file:
    - docker/log.env
    volumes:
    - '/var/run/docker.sock:/tmp/docker.sock'

volumes:
  mrt-files:
    driver: local
  mrt-data:
    driver: local
