version: '2.1'

services:

  mediaserver:
    container_name: mrt.nginx
    restart: on-failure

  app:
    container_name: mrt.app
    restart: on-failure
    environment:
     - FLASK_MIGRATE=no
     - FLASK_CREATE_SUPERUSER=no
    healthcheck:
      test: "curl -f --max-time 1 http://localhost:5000 || exit 1"
      interval: 10s
      timeout: 2s
      retries: 3

  async:
    container_name: mrt.rq
    restart: on-failure

  redis:
    container_name: mrt.redis
    restart: on-failure

  db:
    container_name: mrt.db
    restart: on-failure

  log:
    image: gliderlabs/logspout:v3.2.5
    container_name: mrt.logs
    restart: on-failure
    environment:
     - SYSLOG_HOSTNAME=${HOSTNAME}_{{ index .Container.Config.Labels "com.docker.compose.project"}}
     - LOGSPOUT=ignore
    env_file:
      - docker/log.env
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    command: 'syslog://$${HOST}:$${PORT}?filter.name=$${FILTER}'

volumes:
  app-files:
    driver: local
  app-data:
    driver: local
