"""queue on job

Revision ID: 1155971cef4
Revises: 1c1161bfbead
Create Date: 2014-09-09 15:29:13.689353

"""

# revision identifiers, used by Alembic.
revision = '1155971cef4'
down_revision = '1c1161bfbead'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('queue', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'queue')
    ### end Alembic commands ###
