"""Changed type from PhraseDefault

Revision ID: 116cbf4cb82
Revises: 49362522c008
Create Date: 2014-07-29 16:25:21.814014

"""

# revision identifiers, used by Alembic.
revision = '116cbf4cb82'
down_revision = '49362522c008'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase_default', sa.Column('meeting_type',
                  sa.Unicode(length=255), nullable=False))
    op.drop_column('phrase_default', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase_default', sa.Column('type', sa.VARCHAR(length=255),
                  autoincrement=False, nullable=False))
    op.drop_column('phrase_default', 'meeting_type')
    ### end Alembic commands ###
