"""Participant meeting and category null

Revision ID: 11bb51411e6b
Revises: 2215768d031e
Create Date: 2014-11-05 15:27:43.338231

"""

# revision identifiers, used by Alembic.
revision = '11bb51411e6b'
down_revision = '2215768d031e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participant', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participant', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
