"""job table for rq

Revision ID: 11fdb09ca879
Revises: d4839030d26
Create Date: 2014-09-02 17:19:47.390415

"""

# revision identifiers, used by Alembic.
revision = '11fdb09ca879'
down_revision = 'd4839030d26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    ### end Alembic commands ###
