"""meeting type label to title

Revision ID: 139300f95501
Revises: 94e3554cc38
Create Date: 2014-07-15 16:41:51.779068

"""

# revision identifiers, used by Alembic.
revision = '139300f95501'
down_revision = '94e3554cc38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_type', sa.Column('title', sa.String(length=32), nullable=False))
    op.drop_column('meeting_type', 'label')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_type', sa.Column('label', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('meeting_type', 'title')
    ### end Alembic commands ###
