"""is_visible and is_required for Action model

Revision ID: 14b482ad5574
Revises: 280a266be4a4
Create Date: 2015-01-22 12:24:56.428785

"""

# revision identifiers, used by Alembic.
revision = '14b482ad5574'
down_revision = '280a266be4a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('is_required', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.drop_column('action', 'action_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('action_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('action', 'is_visible')
    op.drop_column('action', 'is_required')
    ### end Alembic commands ###
