"""meeting_id on job table

Revision ID: 1c1161bfbead
Revises: 1b47bf052703
Create Date: 2014-09-05 16:03:18.524544

"""

# revision identifiers, used by Alembic.
revision = '1c1161bfbead'
down_revision = '1b47bf052703'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'representing',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('category_default', 'representing',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('job', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.alter_column('job', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('media_participant', 'title',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_participant', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('job', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('job', 'meeting_id')
    op.alter_column('category_default', 'representing',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('category', 'representing',
               existing_type=sa.ChoiceType(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    ### end Alembic commands ###
