"""meeting venue state and zip code

Revision ID: 1c81eeda2cfa
Revises: 416eafdc222d
Create Date: 2014-07-17 16:55:47.204266

"""

# revision identifiers, used by Alembic.
revision = '1c81eeda2cfa'
down_revision = '416eafdc222d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('venue_code', sa.String(length=16), nullable=True))
    op.add_column('meeting', sa.Column('venue_state', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'venue_state')
    op.drop_column('meeting', 'venue_code')
    ### end Alembic commands ###
