"""participant type

Revision ID: 1d9702e91c2d
Revises: c7e384b1992
Create Date: 2014-11-25 16:47:21.042254

"""

# revision identifiers, used by Alembic.
revision = '1d9702e91c2d'
down_revision = 'c7e384b1992'

from alembic import op
import sqlalchemy as sa
from mrt.models import Participant


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'participant',
        sa.Column('participant_type', sa.Unicode(length=255),
                  nullable=False,
                  server_default=Participant.PARTICIPANT))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'participant_type')
    ### end Alembic commands ###
