"""Added attended field to participant

Revision ID: 1e75b6e97e4e
Revises: 11fdb09ca879
Create Date: 2014-09-03 12:29:30.013031

"""

# revision identifiers, used by Alembic.
revision = '1e75b6e97e4e'
down_revision = '11fdb09ca879'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('attended', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'attended')
    ### end Alembic commands ###
