"""index for registration_token

Revision ID: 2215768d031e
Revises: 4fdfb1b91f97
Create Date: 2014-11-04 17:51:01.967622

"""

# revision identifiers, used by Alembic.
revision = '2215768d031e'
down_revision = '4fdfb1b91f97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'participant', ['registration_token'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant')
    ### end Alembic commands ###
