"""custom field protected

Revision ID: 233aaf9866c6
Revises: 297d2d70c626
Create Date: 2015-04-24 16:40:53.073549

"""

# revision identifiers, used by Alembic.
revision = '233aaf9866c6'
down_revision = '297d2d70c626'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('is_protected', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_field', 'is_protected')
    ### end Alembic commands ###
