"""default phrases

Revision ID: 2498ffa3ad9d
Revises: aacbf9fb66e
Create Date: 2014-08-07 12:12:05.360484

"""

# revision identifiers, used by Alembic.
revision = '2498ffa3ad9d'
down_revision = 'aacbf9fb66e'


from alembic import op
import sqlalchemy as sa
from mrt.models import PhraseDefault


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    phrase_table = PhraseDefault.__table__

    op.bulk_insert(
        phrase_table,
        [
            #COP
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'cop', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'cop', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'cop', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'cop', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'cop', 'sort': 14},

            #AC
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'ac', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'ac', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'ac', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'ac', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'ac', 'sort': 14},

            #scc
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'scc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'scc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'scc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'scc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'scc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'scc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'scc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'scc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'scc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'scc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'scc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'scc', 'sort': 14},

            #sc
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'sc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'sc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'sc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'sc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'sc', 'sort': 14},

            #PC
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'pc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'pc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'pc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'pc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'pc', 'sort': 14},
        ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
