"""Active field on User

Revision ID: 266b910a92f1
Revises: 29c64b2a9a6e
Create Date: 2014-10-30 11:02:57.663596

"""

# revision identifiers, used by Alembic.
revision = '266b910a92f1'
down_revision = '29c64b2a9a6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=False,
                  server_default='1'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    ### end Alembic commands ###
