"""increase column size for custom field value

Revision ID: 273a70e8bc07
Revises: 2b41f923d88d
Create Date: 2015-01-15 12:25:24.227137

"""

# revision identifiers, used by Alembic.
revision = '273a70e8bc07'
down_revision = '236434afb81a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_field_value', 'value',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_field_value', 'value',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    ### end Alembic commands ###
