"""UserNotificationConstraint

Revision ID: 28ee7c8f487e
Revises: 4b7e27bf441c
Create Date: 2014-08-28 18:02:50.111509

"""

# revision identifiers, used by Alembic.
revision = '28ee7c8f487e'
down_revision = '4b7e27bf441c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.create_unique_constraint(None, 'user_notification', ['user_id', 'meeting_id', 'notification_type'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_notification')
    ### end Alembic commands ###
