"""custom field max length

Revision ID: 297d2d70c626
Revises: 446cfda648e
Create Date: 2015-04-15 17:24:32.765445

"""

# revision identifiers, used by Alembic.
revision = '297d2d70c626'
down_revision = '446cfda648e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('max_length', sa.Integer(), nullable=True))
    op.drop_column('custom_field', 'size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('custom_field', 'max_length')
    ### end Alembic commands ###
