"""is_superuser

Revision ID: 29be66728c0e
Revises: 305b4f47828c
Create Date: 2014-11-14 15:29:38.305625

"""

# revision identifiers, used by Alembic.
revision = '29be66728c0e'
down_revision = '305b4f47828c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('is_superuser', sa.Boolean(), nullable=False,
                  server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    ### end Alembic commands ###
