"""Initial migration

Revision ID: 29ecac35d8b2
Revises: None
Create Date: 2014-12-16 18:07:39.940638

"""

# revision identifiers, used by Alembic.
revision = '29ecac35d8b2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_type',
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('recover_token', sa.String(length=64), nullable=True),
    sa.Column('recover_time', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('permissions', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('french', sa.Text(), nullable=True),
    sa.Column('spanish', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_default',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('background', sa.String(length=64), nullable=True),
    sa.Column('representing', sa.Unicode(255), nullable=True),
    sa.Column('category_type', sa.Unicode(255), nullable=False),
    sa.Column('group', sa.Unicode(255), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('visible_on_registration_form', sa.Boolean(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase_default',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('meeting_type', sa.String(length=16), nullable=False),
    sa.Column('description_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['description_id'], ['translation.id'], ),
    sa.ForeignKeyConstraint(['meeting_type'], ['meeting_type.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('badge_header_id', sa.Integer(), nullable=True),
    sa.Column('acronym', sa.String(length=16), nullable=False),
    sa.Column('meeting_type', sa.String(length=16), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('venue_address', sa.String(length=128), nullable=True),
    sa.Column('venue_city_id', sa.Integer(), nullable=False),
    sa.Column('venue_country', sa.String(2), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('online_registration', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.String(), nullable=True),
    sa.Column('photo_field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['badge_header_id'], ['translation.id'], ),
    sa.ForeignKeyConstraint(['meeting_type'], ['meeting_type.slug'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['photo_field_id'], ['custom_field.id'], name='fk_photo_field', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['title_id'], ['translation.id'], ),
    sa.ForeignKeyConstraint(['venue_city_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('field_type', sa.Unicode(255), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('visible_on_registration_form', sa.Boolean(), nullable=True),
    sa.Column('custom_field_type', sa.Unicode(255), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['translation.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'slug', 'custom_field_type')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('background', sa.String(length=64), nullable=True),
    sa.Column('representing', sa.Unicode(255), nullable=True),
    sa.Column('category_type', sa.Unicode(255), nullable=False),
    sa.Column('group', sa.Unicode(255), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('visible_on_registration_form', sa.Boolean(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Unicode(255), nullable=False),
    sa.Column('queue', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meeting_id', 'notification_type')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('description_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['description_id'], ['translation.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Unicode(255), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.Unicode(255), nullable=False),
    sa.Column('country', sa.String(2), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('represented_country', sa.String(2), nullable=True),
    sa.Column('represented_region', sa.Unicode(255), nullable=True),
    sa.Column('represented_organization', sa.String(length=64), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('credentials', sa.Boolean(), nullable=True),
    sa.Column('registration_token', sa.String(length=64), nullable=True),
    sa.Column('participant_type', sa.Unicode(255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_token')
    )
    op.create_table('custom_field_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choice_id'], ['custom_field_choice.id'], ),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'participant_id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_log')
    op.drop_table('activity_log')
    op.drop_table('custom_field_value')
    op.drop_table('custom_field_choice')
    op.drop_table('participant')
    op.drop_table('phrase')
    op.drop_table('user_notification')
    op.drop_table('job')
    op.drop_table('role_user')
    op.drop_table('category')
    op.drop_table('custom_field')
    op.drop_table('meeting')
    op.drop_table('staff')
    op.drop_table('phrase_default')
    op.drop_table('category_default')
    op.drop_table('translation')
    op.drop_table('role')
    op.drop_table('user')
    op.drop_table('meeting_type')
    ### end Alembic commands ###
