"""custom field meeting_id nullable=True

Revision ID: 2a0c02c3cfc
Revises: 11bb51411e6b
Create Date: 2014-11-06 16:34:54.719891

"""

# revision identifiers, used by Alembic.
revision = '2a0c02c3cfc'
down_revision = '11bb51411e6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_field', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_field', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
