"""change category color type

Revision ID: 2d61887c6191
Revises: 4190aa8fe060
Create Date: 2014-07-30 11:17:59.719012

"""

# revision identifiers, used by Alembic.
revision = '2d61887c6191'
down_revision = '4190aa8fe060'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'color',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.alter_column('category_default', 'color',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=7),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_default', 'color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('category', 'color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    ### end Alembic commands ###
