"""Changed description name from Phrase

Revision ID: 2d6e0e5bc24e
Revises: 403a9362da34
Create Date: 2014-07-30 16:13:33.027648

"""

# revision identifiers, used by Alembic.
revision = '2d6e0e5bc24e'
down_revision = '403a9362da34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase', sa.Column('description_id', sa.Integer(), nullable=True))
    op.drop_column('phrase', 'description_translation_id')
    op.add_column('phrase_default', sa.Column('description_id', sa.Integer(), nullable=True))
    op.drop_column('phrase_default', 'description_translation_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase_default', sa.Column('description_translation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('phrase_default', 'description_id')
    op.add_column('phrase', sa.Column('description_translation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('phrase', 'description_id')
    ### end Alembic commands ###
