"""meeting venue city not nullable

Revision ID: 2dcb28543132
Revises: 139300f95501
Create Date: 2014-07-16 17:02:07.395719

"""

# revision identifiers, used by Alembic.
revision = '2dcb28543132'
down_revision = '139300f95501'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'venue_city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'venue_city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
