"""update email column to 128

Revision ID: 2e90b8948231
Revises: 2ef3cf261b48
Create Date: 2015-01-09 18:58:02.237121

"""

# revision identifiers, used by Alembic.
revision = '2e90b8948231'
down_revision = '2ef3cf261b48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    ### end Alembic commands ###
