"""Added FK to participant on ActivityLog

Revision ID: 2f4220e008ea
Revises: 46e67610c62
Create Date: 2014-08-21 15:18:13.792500

"""

# revision identifiers, used by Alembic.
revision = '2f4220e008ea'
down_revision = '46e67610c62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_log', 'participant_name')
    op.alter_column('activity_log', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('activity_log', sa.Column('participant_name', sa.VARCHAR(length=64), autoincrement=False))
    ### end Alembic commands ###
