"""custom field unique constraint, meeting_id and slug

Revision ID: 305b4f47828c
Revises: 558d8948b61f
Create Date: 2014-11-10 18:00:01.674157

"""

# revision identifiers, used by Alembic.
revision = '305b4f47828c'
down_revision = '558d8948b61f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_custom_field', 'custom_field', ['meeting_id', 'slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_custom_field', 'custom_field')
    ### end Alembic commands ###
