"""added rule type field

Revision ID: 30a9520acd9f
Revises: 545e26d5a909
Create Date: 2016-03-24 10:55:37.952670

"""

# revision identifiers, used by Alembic.
revision = '30a9520acd9f'
down_revision = '545e26d5a909'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('rule_type',  sa.Unicode(255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'rule_type')
    ### end Alembic commands ###
