"""custom field sort

Revision ID: 30d68ffd9442
Revises: 2498ffa3ad9d
Create Date: 2014-08-13 15:59:53.032204

"""

# revision identifiers, used by Alembic.
revision = '30d68ffd9442'
down_revision = '2498ffa3ad9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('sort', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_field', 'sort')
    ### end Alembic commands ###
