"""name on badge 20 chars

Revision ID: 310aa3328e89
Revises: 1bf21383b2f
Create Date: 2015-04-15 16:44:00.078656

"""

# revision identifiers, used by Alembic.
revision = '310aa3328e89'
down_revision = '1bf21383b2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'badge_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=20),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'badge_name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    ### end Alembic commands ###
