"""Media photo field on meeting

Revision ID: 333833cebe88
Revises: 280a266be4a4
Create Date: 2015-01-22 10:48:26.499266

"""

# revision identifiers, used by Alembic.
revision = '333833cebe88'
down_revision = '280a266be4a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('media_photo_field_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'media_photo_field_id')
    ### end Alembic commands ###
