"""Add default meeting type.

Revision ID: 356917e1326c
Revises: 42fad7c5fc31
Create Date: 2014-12-08 17:58:08.352337

"""

# revision identifiers, used by Alembic.
revision = '356917e1326c'
down_revision = '42fad7c5fc31'

from alembic import op
from mrt.models import MeetingType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    meeting_type_table = MeetingType.__table__
    op.bulk_insert(
        meeting_type_table,
        [
            {'slug': 'def',  'label': 'Default Meeting', 'default': True},
        ])
    op.create_foreign_key('fk_meetingtype_meeting',
                          'meeting', 'meeting_type',
                          ['meeting_type'], ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_meetingtype_meeting', 'meeting')
    ### end Alembic commands ###
