"""staff_update

Revision ID: 364dff96b435
Revises: 29f4ff056a79
Create Date: 2014-07-16 13:27:37.167508

"""

# revision identifiers, used by Alembic.
revision = '364dff96b435'
down_revision = '29f4ff056a79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('full_name', sa.String(length=128), nullable=False))
    op.add_column('staff', sa.Column('title', sa.String(length=64), nullable=True))
    op.alter_column('staff', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('staff', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('staff', 'title')
    op.drop_column('staff', 'full_name')
    ### end Alembic commands ###
