"""remove meeting type

Revision ID: 37d0455677cd
Revises: 5a03fb04b943
Create Date: 2014-07-17 12:31:48.253558

"""

# revision identifiers, used by Alembic.
revision = '37d0455677cd'
down_revision = '5a03fb04b943'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('meeting_type', sa.String(length=3), nullable=False))
    op.drop_column('meeting', 'meeting_type_id')
    op.drop_table('meeting_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('meeting_type_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('meeting', 'meeting_type')
    op.create_table('meeting_type',
    sa.Column('slug', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('slug', name=u'meeting_type_pkey')
    )
    ### end Alembic commands ###
