"""Added category class table

Revision ID: 381739c14b7d
Revises: 589ab4d20cc6
Create Date: 2015-08-18 17:03:24.958982

"""

# revision identifiers, used by Alembic.
revision = '381739c14b7d'
down_revision = '589ab4d20cc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_class',
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.add_column(u'category', sa.Column('category_class_slug', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'category', 'category_class', ['category_class_slug'], ['slug'])
    op.add_column(u'category_default', sa.Column('category_class_slug', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'category_default', 'category_class', ['category_class_slug'], ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_default', type_='foreignkey')
    op.drop_column(u'category_default', 'category_class_slug')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column(u'category', 'category_class_slug')
    op.drop_table('category_class')
    ### end Alembic commands ###
