"""RoleUser meeting nullable false

Revision ID: 394553a02af1
Revises: 1d70ecd3db0d
Create Date: 2014-12-18 15:25:12.527526

"""

# revision identifiers, used by Alembic.
revision = '394553a02af1'
down_revision = '1d70ecd3db0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_user', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_user', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
