"""Added category class table

Revision ID: 396eae9a08aa
Revises: 589ab4d20cc6
Create Date: 2015-08-19 13:13:56.677881

"""

# revision identifiers, used by Alembic.
revision = '396eae9a08aa'
down_revision = '589ab4d20cc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'category', sa.Column('category_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'category_class', ['category_class_id'], ['id'])
    op.add_column(u'category_default', sa.Column('category_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category_default', 'category_class', ['category_class_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_default', type_='foreignkey')
    op.drop_column(u'category_default', 'category_class_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column(u'category', 'category_class_id')
    op.drop_table('category_class')
    ### end Alembic commands ###
