"""Country on Participant is nullable

Revision ID: 39ffcca9afb1
Revises: 49f5e88ffa53
Create Date: 2014-11-27 12:39:54.160181

"""

# revision identifiers, used by Alembic.
revision = '39ffcca9afb1'
down_revision = '49f5e88ffa53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_participant')
    op.alter_column('participant', 'country',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'country',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.create_table('media_participant',
    sa.Column('id', sa.INTEGER(), server_default="nextval('media_participant_id_seq'::regclass)", nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], [u'category.id'], name=u'media_participant_category_id_fkey'),
    sa.ForeignKeyConstraint(['meeting_id'], [u'meeting.id'], name=u'media_participant_meeting_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'media_participant_pkey')
    )
    ### end Alembic commands ###
