"""add name on the badge

Revision ID: 3bd48ad4187a
Revises: 4c94c61c9545
Create Date: 2015-03-17 06:02:27.258594

"""

# revision identifiers, used by Alembic.
revision = '3bd48ad4187a'
down_revision = '4c94c61c9545'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('badge_name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'badge_name')
    ### end Alembic commands ###
