"""ActivityLog add

Revision ID: 3cbf4b74f3ad
Revises: 14726375a6a0
Create Date: 2014-08-14 12:36:01.660660

"""

# revision identifiers, used by Alembic.
revision = '3cbf4b74f3ad'
down_revision = '14726375a6a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('participant_name', sa.String(length=64), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_log')
    ### end Alembic commands ###
