"""remove unique constraint for custom_field_value table

Revision ID: 3edad7178c45
Revises: 76af46664fc
Create Date: 2015-03-30 14:01:44.803841

"""

# revision identifiers, used by Alembic.
revision = '3edad7178c45'
down_revision = '76af46664fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'custom_field_value_custom_field_id_participant_id_key', 'custom_field_value', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'custom_field_value_custom_field_id_participant_id_key', 'custom_field_value', ['custom_field_id', 'participant_id'])
    ### end Alembic commands ###
