"""insert default phrases

Revision ID: 4010abfe2f2b
Revises: 49362522c008
Create Date: 2014-07-29 11:03:10.985039

"""

# revision identifiers, used by Alembic.
revision = '4010abfe2f2b'
down_revision = '49362522c008'

from alembic import op
from mrt.models import PhraseDefault


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    phrase_table = PhraseDefault.__table__

    op.bulk_insert(
        phrase_table,
        [
            #COP
            {'name': 'Body', 'group': 'Acknowledge email',
             'type': 'cop', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'type': 'cop', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'type': 'cop', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'type': 'cop', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'type': 'cop', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'type': 'cop', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'type': 'cop', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'type': 'cop', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'type': 'cop', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'type': 'cop', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'type': 'cop', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'type': 'cop', 'sort': 14},

            #AC
            {'name': 'Body', 'group': 'Acknowledge email',
             'type': 'ac', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'type': 'ac', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'type': 'ac', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'type': 'ac', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'type': 'ac', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'type': 'ac', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'type': 'ac', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'type': 'ac', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'type': 'ac', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'type': 'ac', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'type': 'ac', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'type': 'ac', 'sort': 14},

            #SC
            {'name': 'Body', 'group': 'Acknowledge email',
             'type': 'sc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'type': 'sc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'type': 'sc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'type': 'sc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'type': 'sc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'type': 'sc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'type': 'sc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'type': 'sc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'type': 'sc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'type': 'sc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'type': 'sc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'type': 'sc', 'sort': 14},

            #STC
            {'name': 'Body', 'group': 'Acknowledge email',
             'type': 'stc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'type': 'stc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'type': 'stc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'type': 'stc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'type': 'stc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'type': 'stc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'type': 'stc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'type': 'stc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'type': 'stc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'type': 'stc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'type': 'stc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'type': 'stc', 'sort': 14},

            #PC
            {'name': 'Body', 'group': 'Acknowledge email',
             'type': 'pc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'type': 'pc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'type': 'pc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'type': 'pc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'type': 'pc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'type': 'pc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'type': 'pc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'type': 'pc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'type': 'pc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'type': 'pc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'type': 'pc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'type': 'pc', 'sort': 14},
        ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
