"""added is_active on user

Revision ID: 401778722c52
Revises: 1c81eeda2cfa
Create Date: 2014-07-21 10:41:58.176092

"""

# revision identifiers, used by Alembic.
revision = '401778722c52'
down_revision = '1c81eeda2cfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
