"""change category name to title

Revision ID: 403a9362da34
Revises: 2d61887c6191
Create Date: 2014-07-30 16:55:54.609298

"""

# revision identifiers, used by Alembic.
revision = '403a9362da34'
down_revision = '2d61887c6191'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('title_id', sa.Integer(), nullable=False))
    op.drop_column('category', 'name_id')
    op.add_column('category_default', sa.Column('title_id', sa.Integer(), nullable=False))
    op.drop_column('category_default', 'name_id')
    op.alter_column('participant', 'title',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.add_column('category_default', sa.Column('name_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('category_default', 'title_id')
    op.add_column('category', sa.Column('name_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('category', 'title_id')
    ### end Alembic commands ###
