"""country field to participant

Revision ID: 40a901b1b87a
Revises: 2d6e0e5bc24e
Create Date: 2014-08-04 12:20:14.934650

"""

# revision identifiers, used by Alembic.
revision = '40a901b1b87a'
down_revision = '2d6e0e5bc24e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('country', sa.String(length=2),
                  nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'country')
    ### end Alembic commands ###
