"""Insert DefaultPhrases

Revision ID: 4190aa8fe060
Revises: 116cbf4cb82
Create Date: 2014-07-29 16:26:55.047831

"""

# revision identifiers, used by Alembic.
revision = '4190aa8fe060'
down_revision = '116cbf4cb82'

from alembic import op
from mrt.models import PhraseDefault


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    phrase_table = PhraseDefault.__table__

    op.bulk_insert(
        phrase_table,
        [
            #COP
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'cop', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'cop', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'cop', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'cop', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'cop', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'cop', 'sort': 14},

            #AC
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'ac', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'ac', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'ac', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'ac', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'ac', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'ac', 'sort': 14},

            #SC
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'sc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'sc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'sc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'sc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'sc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'sc', 'sort': 14},

            #STC
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'stc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'stc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'stc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'stc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'stc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'stc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'stc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'stc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'stc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'stc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'stc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'stc', 'sort': 14},

            #PC
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'pc', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'pc', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'pc', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'pc', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'pc', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'pc', 'sort': 14},
        ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
