"""category visible on registration form

Revision ID: 42707257d9e8
Revises: 4de564070637
Create Date: 2014-10-08 16:43:47.380646

"""

# revision identifiers, used by Alembic.
revision = '42707257d9e8'
down_revision = '4de564070637'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('visible_on_registration_form', sa.Boolean(), nullable=True))
    op.add_column('category_default', sa.Column('visible_on_registration_form', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_default', 'visible_on_registration_form')
    op.drop_column('category', 'visible_on_registration_form')
    ### end Alembic commands ###
