"""custom field size

Revision ID: 446cfda648e
Revises: 310aa3328e89
Create Date: 2015-04-15 17:06:41.290151

"""

# revision identifiers, used by Alembic.
revision = '446cfda648e'
down_revision = '310aa3328e89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_field', 'size')
    ### end Alembic commands ###
