"""remove venue_city and venue_code

Revision ID: 4560afdd7d4f
Revises: 4755da86bd9a
Create Date: 2014-07-25 11:31:11.100432

"""

# revision identifiers, used by Alembic.
revision = '4560afdd7d4f'
down_revision = '4755da86bd9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'venue_state')
    op.drop_column('meeting', 'venue_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('venue_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('meeting', sa.Column('venue_state', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    ### end Alembic commands ###
