"""Initial migration

Revision ID: 45acac6b32fd
Revises: None
Create Date: 2014-08-05 18:16:04.526727

"""

# revision identifiers, used by Alembic.
revision = '45acac6b32fd'
down_revision = None

from alembic import op
import sqlalchemy as sa
from mrt.models import JSONEncodedDict

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('permissions', JSONEncodedDict(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('recover_token', sa.String(length=64), nullable=True),
    sa.Column('recover_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('french', sa.Text(), nullable=True),
    sa.Column('spanish', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase_default',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('meeting_type', sa.String(length=255), nullable=False),
    sa.Column('description_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['description_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_default',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('background', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('acronym', sa.String(length=16), nullable=False),
    sa.Column('meeting_type', sa.String(length=3), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('venue_address', sa.String(length=128), nullable=True),
    sa.Column('venue_city_id', sa.Integer(), nullable=False),
    sa.Column('venue_country', sa.String(length=2), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('online_registration', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['translation.id'], ),
    sa.ForeignKeyConstraint(['venue_city_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('description_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['description_id'], ['translation.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('background', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choice_id'], ['custom_field_choice.id'], ),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_field_value')
    op.drop_table('custom_field_choice')
    op.drop_table('participant')
    op.drop_table('media_participant')
    op.drop_table('custom_field')
    op.drop_table('category')
    op.drop_table('role_user')
    op.drop_table('phrase')
    op.drop_table('meeting')
    op.drop_table('staff')
    op.drop_table('category_default')
    op.drop_table('phrase_default')
    op.drop_table('translation')
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
