"""Added deleted flag on participant

Revision ID: 46e67610c62
Revises: 3cbf4b74f3ad
Create Date: 2014-08-21 14:44:49.623688

"""

# revision identifiers, used by Alembic.
revision = '46e67610c62'
down_revision = '3cbf4b74f3ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('deleted', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'deleted')
    ### end Alembic commands ###
