"""Remove admin/media_admin from Meeting - replaced with owner

Revision ID: 4755da86bd9a
Revises: f24cb4c46e2
Create Date: 2014-07-24 10:42:14.352869

"""

# revision identifiers, used by Alembic.
revision = '4755da86bd9a'
down_revision = 'f24cb4c46e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_column('meeting', 'media_admin_name')
    op.drop_column('meeting', 'admin_name')
    op.drop_column('meeting', 'media_admin_email')
    op.drop_column('meeting', 'admin_email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('admin_email', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('meeting', sa.Column('media_admin_email', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('meeting', sa.Column('admin_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('meeting', sa.Column('media_admin_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('meeting', 'owner_id')
    ### end Alembic commands ###
