"""added translatable hint field

Revision ID: 47996bf2842d
Revises: 1a1703217f7b
Create Date: 2015-05-11 16:34:36.640163

"""

# revision identifiers, used by Alembic.
revision = '47996bf2842d'
down_revision = '1a1703217f7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('hint_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'custom_field', 'translation', ['hint_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_field', type_='foreignkey')
    op.drop_column('custom_field', 'hint_id')
    ### end Alembic commands ###
