"""Custom field is_primary column

Revision ID: 47f427245619
Revises: 42707257d9e8
Create Date: 2014-10-09 17:20:58.319788

"""

# revision identifiers, used by Alembic.
revision = '47f427245619'
down_revision = '42707257d9e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('is_primary', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_field', 'is_primary')
    ### end Alembic commands ###
