"""credentials and verified columns

Revision ID: 47f6ac2751f4
Revises: 53ee924603d0
Create Date: 2014-10-10 17:42:22.532670

"""

# revision identifiers, used by Alembic.
revision = '47f6ac2751f4'
down_revision = '53ee924603d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('credentials', sa.Boolean(), nullable=True))
    op.add_column('participant', sa.Column('verified', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'verified')
    op.drop_column('participant', 'credentials')
    ### end Alembic commands ###
