"""Added default phrase

Revision ID: 49362522c008
Revises: 5ad75807ddda
Create Date: 2014-07-29 11:01:59.758339

"""

# revision identifiers, used by Alembic.
revision = '49362522c008'
down_revision = '5ad75807ddda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'phrase_default',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('group', sa.String(length=32), nullable=True),
        sa.Column('sort', sa.Integer(), nullable=True),
        sa.Column('type', sa.Unicode(length=255), nullable=False),
        sa.Column('description_translation_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['description_translation_id'],
                                ['translation.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'phrase', sa.Column('description_translation_id',
                  sa.Integer(), nullable=True))
    op.drop_column(u'phrase', 'descpription_translation_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'phrase', sa.Column('descpription_translation_id',
                  sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column(u'phrase', 'description_translation_id')
    op.drop_table('phrase_default')
    ### end Alembic commands ###
