"""unique constraint for CustomFieldValue

Revision ID: 4a26e5a36d99
Revises: 2f4220e008ea
Create Date: 2014-08-22 15:33:13.039552

"""

# revision identifiers, used by Alembic.
revision = '4a26e5a36d99'
down_revision = '2f4220e008ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'custom_field_value', ['custom_field_id', 'participant_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_field_value')
    ### end Alembic commands ###
