"""Added UserNotification

Revision ID: 4b7e27bf441c
Revises: 4a26e5a36d99
Create Date: 2014-08-26 16:02:18.529334

"""

# revision identifiers, used by Alembic.
revision = '4b7e27bf441c'
down_revision = '4a26e5a36d99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notification')
    ### end Alembic commands ###
