"""Added represeting fields to participant

Revision ID: 4bc86157e7bf
Revises: 1e75b6e97e4e
Create Date: 2014-09-04 12:03:45.746650

"""

# revision identifiers, used by Alembic.
revision = '4bc86157e7bf'
down_revision = '1e75b6e97e4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column('participant', sa.Column('represented_country',
                  sa.String(length=2), nullable=True))
    op.add_column('participant', sa.Column('represented_organization',
                  sa.String(length=64), nullable=True))
    op.add_column('participant', sa.Column('represented_region',
                  sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'represented_region')
    op.drop_column('participant', 'represented_organization')
    op.drop_column('participant', 'represented_country')
    ### end Alembic commands ###
