"""add missing fk

Revision ID: 4c94c61c9545
Revises: 161e7b674e1c
Create Date: 2015-03-06 16:39:59.455333

"""

# revision identifiers, used by Alembic.
revision = '4c94c61c9545'
down_revision = '161e7b674e1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_photo_field', 'meeting', 'custom_field', ['photo_field_id'], ['id'])
    op.create_foreign_key('fk_media_photo_field', 'meeting', 'custom_field', ['media_photo_field_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_media_photo_field', 'meeting', type_='foreignkey')
    op.drop_constraint('fk_photo_field', 'meeting', type_='foreignkey')
    ### end Alembic commands ###
