"""category type and group

Revision ID: 4de564070637
Revises: 1155971cef4
Create Date: 2014-10-08 16:02:05.836656

"""

# revision identifiers, used by Alembic.
revision = '4de564070637'
down_revision = '1155971cef4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'category',
        sa.Column('category_type', sa.VARCHAR(length=255), nullable=False,
                  server_default='participant'))
    op.add_column(
        'category',
        sa.Column('group', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('category', 'type')
    op.add_column(
        'category_default',
        sa.Column('category_type', sa.VARCHAR(length=255), nullable=False,
                  server_default='participant'))
    op.add_column(
        'category_default',
        sa.Column('group', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('category_default', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'category_default',
        sa.Column('type', sa.VARCHAR(length=255), autoincrement=False,
                  nullable=False))
    op.drop_column('category_default', 'group')
    op.drop_column('category_default', 'category_type')
    op.add_column(
        'category',
        sa.Column('type', sa.VARCHAR(length=255), autoincrement=False,
                  nullable=False))
    op.drop_column('category', 'group')
    op.drop_column('category', 'category_type')
    ### end Alembic commands ###
