"""Added Role and RoleUser

Revision ID: 4e077fb52d62
Revises: 2d6e0e5bc24e
Create Date: 2014-08-04 11:41:55.472317

"""

# revision identifiers, used by Alembic.
revision = '4e077fb52d62'
down_revision = '2d6e0e5bc24e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'role', sa.Column('name', sa.String(length=32), nullable=False))
    op.add_column(u'role', sa.Column('permissions', postgresql.JSON(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'role', 'permissions')
    op.drop_column(u'role', 'name')
    op.drop_table('role_user')
    ### end Alembic commands ###
