"""custom field type choice and label

Revision ID: 4e316c86289d
Revises: b0cdfe3c472
Create Date: 2014-08-05 18:24:27.968594

"""

# revision identifiers, used by Alembic.
revision = '4e316c86289d'
down_revision = 'b0cdfe3c472'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('label', sa.String(length=32), nullable=False))
    op.alter_column('custom_field', 'type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_field', 'type',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('custom_field', 'label')
    ### end Alembic commands ###
