"""Registration token on Participant

Revision ID: 4fdfb1b91f97
Revises: 266b910a92f1
Create Date: 2014-10-31 12:05:07.688136

"""

# revision identifiers, used by Alembic.
revision = '4fdfb1b91f97'
down_revision = '266b910a92f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('registration_token', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'registration_token')
    ### end Alembic commands ###
