"""category background nullable=False

Revision ID: 52ff46a0097a
Revises: 401778722c52
Create Date: 2014-07-22 16:58:26.735500

"""

# revision identifiers, used by Alembic.
revision = '52ff46a0097a'
down_revision = '401778722c52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'background',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('category_default', 'background',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_default', 'background',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('category', 'background',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    ### end Alembic commands ###
