"""Change the JSON type from Role

Revision ID: 53215e657f1c
Revises: c3d8dfe84e3
Create Date: 2014-08-05 15:05:32.393277

"""

# revision identifiers, used by Alembic.
revision = '53215e657f1c'
down_revision = 'c3d8dfe84e3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from mrt.models import JSONEncodedDict


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('country', sa.String(length=2), nullable=False))
    op.alter_column('role', 'permissions',
               existing_type=postgresql.JSON(),
               type_=JSONEncodedDict(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'permissions',
               existing_type=JSONEncodedDict(),
               type_=postgresql.JSON(),
               existing_nullable=False)
    op.drop_column('participant', 'country')
    ### end Alembic commands ###
