"""Added custom_field fk on meeting

Revision ID: 53ee924603d0
Revises: 42707257d9e8
Create Date: 2014-10-09 15:33:35.576708

"""

# revision identifiers, used by Alembic.
revision = '53ee924603d0'
down_revision = '42707257d9e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('photo_field_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_photo_field', 'meeting', 'custom_field',
                          ['photo_field_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'photo_field_id')
    ### end Alembic commands ###
