"""add representing attribute

Revision ID: 545e26d5a909
Revises: 200425d3687d
Create Date: 2015-08-24 11:08:22.273757

"""

# revision identifiers, used by Alembic.
revision = '545e26d5a909'
down_revision = '200425d3687d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('representing', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'representing')
    ### end Alembic commands ###
