"""Added Translation, Phrase and Fee

Revision ID: 5692127ecfca
Revises: 26ac73f28bcb
Create Date: 2014-07-09 17:18:01.061582

"""

# revision identifiers, used by Alembic.
revision = '5692127ecfca'
down_revision = '26ac73f28bcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.String(length=128), nullable=False),
    sa.Column('french', sa.String(length=128), nullable=True),
    sa.Column('spanish', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('name_translation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['name_translation_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('descpription_translation_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['descpription_translation_id'], ['translation.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrase')
    op.drop_table('fee')
    op.drop_table('translation')
    ### end Alembic commands ###
