"""custom field visible on registration form

Revision ID: 57e914588132
Revises: 47f6ac2751f4
Create Date: 2014-10-20 18:24:39.728308

"""

# revision identifiers, used by Alembic.
revision = '57e914588132'
down_revision = '47f6ac2751f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('visible_on_registration_form', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_field', 'visible_on_registration_form')
    ### end Alembic commands ###
