"""convert meeting date start and date end to DateField

Revision ID: 5a03fb04b943
Revises: 2dcb28543132
Create Date: 2014-07-16 17:54:10.877237

"""

# revision identifiers, used by Alembic.
revision = '5a03fb04b943'
down_revision = '2dcb28543132'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
