"""change meeting backgroud column size

Revision ID: 5ad75807ddda
Revises: 51d10a95956d
Create Date: 2014-07-28 15:47:40.362811

"""

# revision identifiers, used by Alembic.
revision = '5ad75807ddda'
down_revision = '51d10a95956d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ChoiceType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'background',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('category', 'color',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('category', 'type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('category_default', 'background',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('category_default', 'color',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('category_default', 'type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_default', 'type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('category_default', 'color',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('category_default', 'background',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('category', 'type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('category', 'color',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('category', 'background',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    ### end Alembic commands ###
