"""Populate meeting_type table.

Revision ID: 720b3a7a47a
Revises: 59400008a7ff
Create Date: 2014-12-03 16:47:40.755396

"""

# revision identifiers, used by Alembic.
revision = '720b3a7a47a'
down_revision = '59400008a7ff'

from alembic import op
import sqlalchemy as sa
from mrt.models import MeetingType, PhraseDefault


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    meeting_type_table = MeetingType.__table__
    phrase_table = PhraseDefault.__table__

    op.bulk_insert(
        meeting_type_table,
        [
            {'slug': 'cop', 'label': 'Conference of the Parties'},
            {'slug': 'ac',  'label': 'Animals Committee'},
            {'slug': 'scc', 'label': 'Scientific Council'},
            {'slug': 'sc',  'label': 'Standing Committee'},
            {'slug': 'pc',  'label': 'Plants Committee'},
            {'slug': 'def',  'label': 'Default Meeting'},
        ])
    op.bulk_insert(
        phrase_table,
        [
            {'name': 'Body', 'group': 'Acknowledge email',
             'meeting_type': 'def', 'sort': 1},
            {'name': 'Credentials', 'group': 'Acknowledge details',
             'meeting_type': 'def', 'sort': 3},
            {'name': 'Approval', 'group': 'Acknowledge details',
             'meeting_type': 'def', 'sort': 5},
            {'name': 'Invitation', 'group': 'Acknowledge details',
             'meeting_type': 'def', 'sort': 6},
            {'name': 'Fee', 'group': 'Acknowledge details',
             'meeting_type': 'def', 'sort': 7},
            {'name': 'Payment', 'group': 'Acknowledge details',
             'meeting_type': 'def', 'sort': 8},
            {'name': 'Subject', 'group': 'Acknowledge email',
             'meeting_type': 'def', 'sort': 0},
            {'name': 'for participants',
             'group': 'Online registration confirmation',
             'meeting_type': 'def', 'sort': 9},
            {'name': 'for media',
             'group': 'Online registration confirmation',
             'meeting_type': 'def', 'sort': 10},
            {'name': 'Footer', 'group': 'Acknowledge details',
             'meeting_type': 'def', 'sort': 10},
            {'name': 'Statutes', 'group': 'Acknowledge details',
             'meeting_type': 'def', 'sort': 4},
            {'name': 'for participants',
             'group': 'Email registration confirmation',
             'meeting_type': 'def', 'sort': 14},
        ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
