"""Populate meeting_type table.

Revision ID: 720b3a7a47a
Revises: 59400008a7ff
Create Date: 2014-12-03 16:47:40.755396

"""

# revision identifiers, used by Alembic.
revision = '720b3a7a47a'
down_revision = '59400008a7ff'

from alembic import op
import sqlalchemy as sa
from mrt.models import MeetingType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    meeting_type_table = MeetingType.__table__
    op.bulk_insert(
        meeting_type_table,
        [
            {'slug': 'cop', 'label': 'Conference of the Parties'},
            {'slug': 'ac',  'label': 'Animals Committee'},
            {'slug': 'scc', 'label': 'Scientific Council'},
            {'slug': 'sc',  'label': 'Standing Committee'},
            {'slug': 'pc',  'label': 'Plants Committee'},
            {'slug': 'def',  'label': 'Default Meeting'},
        ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
