"""custom field value nullable

Revision ID: 76af46664fc
Revises: 4c94c61c9545
Create Date: 2015-03-26 17:05:06.079017

"""

# revision identifiers, used by Alembic.
revision = '76af46664fc'
down_revision = '4c94c61c9545'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_field_value', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_field_value', 'value',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###
