"""Add category sorting field

Revision ID: 87a5a6743c72
Revises: a06a21bd4873
Create Date: 2020-01-20 10:24:49.374759

"""

# revision identifiers, used by Alembic.
revision = '87a5a6743c72'
down_revision = 'a06a21bd4873'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('sort_field', sa.Unicode(255), nullable=True))
    op.add_column('category_default', sa.Column('sort_field', sa.Unicode(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_default', 'sort_field')
    op.drop_column('category', 'sort_field')
    # ### end Alembic commands ###
