"""meeting city i18n

Revision ID: 94e3554cc38
Revises: 29f4ff056a79
Create Date: 2014-07-15 15:31:25.621592

"""

# revision identifiers, used by Alembic.
revision = '94e3554cc38'
down_revision = '29f4ff056a79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('venue_city_id', sa.Integer(), nullable=True))
    op.drop_column('meeting', 'venue_city')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('venue_city', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('meeting', 'venue_city_id')
    ### end Alembic commands ###
