"""Add sex field to meeting/participant

Revision ID: 96153f452c5e
Revises: a06a21bd4873
Create Date: 2020-01-20 15:36:42.928173

"""

# revision identifiers, used by Alembic.
revision = '96153f452c5e'
down_revision = 'a06a21bd4873'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('sex', sa.Unicode(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'sex')
    # ### end Alembic commands ###
