"""changed staff role to nullable=false

Revision ID: b34bd8c9b63
Revises: 4e077fb52d62
Create Date: 2014-08-04 15:26:45.777569

"""

# revision identifiers, used by Alembic.
revision = 'b34bd8c9b63'
down_revision = '4e077fb52d62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
