"""Add category sorting field

Revision ID: be56b154667a
Revises: a06a21bd4873
Create Date: 2020-01-20 10:35:24.817726

"""

# revision identifiers, used by Alembic.
revision = "be56b154667a"
down_revision = "a06a21bd4873"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("sort_field", sa.Unicode(255), nullable=True))
    op.add_column(
        "category_default", sa.Column("sort_field", sa.Unicode(255), nullable=True)
    )
    op.execute("UPDATE category SET sort_field='last_name'")
    op.execute("UPDATE category_default SET sort_field='last_name'")
    op.alter_column("category", "sort_field", nullable=False)
    op.alter_column("category_default", "sort_field", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category_default", "sort_field")
    op.drop_column("category", "sort_field")
    # ### end Alembic commands ###
