"""description for custom fields

Revision ID: c7e384b1992
Revises: 29be66728c0e
Create Date: 2014-11-19 18:04:24.197523

"""

# revision identifiers, used by Alembic.
revision = 'c7e384b1992'
down_revision = '29be66728c0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('description', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_field', 'description')
    ### end Alembic commands ###
