"""disable form action

Revision ID: c94e24a0df5
Revises: 30a9520acd9f
Create Date: 2016-04-06 16:37:23.579773

"""

# revision identifiers, used by Alembic.
revision = 'c94e24a0df5'
down_revision = '30a9520acd9f'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('disable_form', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'disable_form')
    ### end Alembic commands ###
