"""Typo on MediaParticipant

Revision ID: f24cb4c46e2
Revises: 52ff46a0097a
Create Date: 2014-07-24 10:25:16.494516

"""

# revision identifiers, used by Alembic.
revision = 'f24cb4c46e2'
down_revision = '52ff46a0097a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('media_paticipant')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_paticipant',
    sa.Column('id', sa.INTEGER(), server_default="nextval('media_paticipant_id_seq'::regclass)", nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], [u'category.id'], name=u'media_paticipant_category_id_fkey'),
    sa.ForeignKeyConstraint(['meeting_id'], [u'meeting.id'], name=u'media_paticipant_meeting_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'media_paticipant_pkey')
    )
    op.drop_table('media_participant')
    ### end Alembic commands ###
